### ISSUE TITLE
Bot seems to be offline.

### ISSUE THREAD

**Issue by Creactus** [xlash123/KHUx-Discord-Bot#44]
I've noticed that over the past few days the bot has been offline, I wanted to bring it to your attention on the off chance that there is an issue that needs to be fixed.

**Comment by shanible** [comment]
It last worked on 06 December for me, right around all those google api errors discord encountered.

**Comment by xlash123** [comment]
Hello. I have noticed that the bot has been tending to unexpectedly shut down without notice or reason. I am currently trying to find a solution, but at the moment, I have found little leads. I also don’t spend much time programming the bot since I have stopped playing the game for well over a year now. I will still try to fix this bug, but please be patient as I am still clueless as to why it keeps happening.

Also, I didn’t know about the Google stuff, but I don’t think it’s related as this issue existed before December 6. 

Edit: I forgot to mention that I can hot fix the issue by restarting the bot every time it goes offline, however it’s pretty unstable and seems to go down within a day.

**Comment by xlash123** [comment]
Huh, it hasn't gone offline in over a week. Perhaps there was a problem on Discord/Google's end. I'll close this issue as it appears to have solved itself.

**Comment by Creactus** [comment]
Now that it's back online it seems to not be accepting commands outside of the base commands that post a description of what they do, such as "!medal" telling you how that command works... but doing "!medal Sora" doesn't post anything. The same is true for the other commands, though some, like "!tweet," aren't posting anything even when using the base command.

**Comment by xlash123** [comment]
Ah, I see the issue. I am on it.

**Comment by Creactus** [comment]
Ty, you're the best!!
